Kontrola/Kontrola/Controllers/ChamadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kontrola.Context;
using Kontrola.Models;
using Microsoft.AspNetCore.Authorization;

namespace Kontrola.Controllers
{

    public class ChamadosController : Controller
    {
        private readonly AppDbContext _context;

        public ChamadosController(AppDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {

            var appDbContext = _context.Chamados.Include(c => c.Gravidade).Include(c => c.Cliente).Include(c => c.Modalidade).Include(c => c.Status).Include(c => c.Tendencia).Include(c => c.Urgencia);
            return View(await appDbContext.ToListAsync());
        }

		[Authorize(Roles = "Membro")]
		public async Task<IActionResult> IndexMembro()
		{

			var appDbContext = _context.Chamados.Include(c => c.Gravidade).Include(c => c.Cliente).Include(c => c.Modalidade).Include(c => c.Status).Include(c => c.Tendencia).Include(c => c.Urgencia);
			return View(await appDbContext.ToListAsync());
		}

		// GET: Chamados/Details/5
		[Authorize(Roles = "Admin,Membro")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Chamados == null)
            {
                return NotFound();
            }

            var chamado = await _context.Chamados
                .Include(c => c.Cliente)
                .Include(c => c.Gravidade)
                .Include(c => c.Modalidade)
                .Include(c => c.Status)
                .Include(c => c.Tendencia)
                .Include(c => c.Urgencia)
                .FirstOrDefaultAsync(m => m.ChamadoId == id);
            if (chamado == null)
            {
                return NotFound();
            }

            return View(chamado);
        }

        // GET: Chamados/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "ClienteId", "Nome");
            ViewData["GravidadeId"] = new SelectList(_context.Gravidades, "GravidadeId", "Descricao");
            ViewData["ModalidadeId"] = new SelectList(_context.Modalidades, "ModalidadeId", "Descricao");
            ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "Descricao");
            ViewData["TendenciaId"] = new SelectList(_context.Tendencias, "TendenciaId", "Descricao");
            ViewData["UrgenciaId"] = new SelectList(_context.Urgencias, "UrgenciaId", "Descricao");
            return View();
        }

        // POST: Chamados/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("ChamadoId,DataInicio,DataFechamento,Descricao,Diagnostico,Pendencia,Conclusao,ClienteId,StatusId,ModalidadeId,GravidadeId,UrgenciaId,TendenciaId")] Chamado chamado)
        {
            if (ModelState.IsValid)
            {
                _context.Add(chamado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "ClienteId", "ClienteId", chamado.ClienteId);
            ViewData["GravidadeId"] = new SelectList(_context.Gravidades, "GravidadeId", "GravidadeId", chamado.GravidadeId);
            ViewData["ModalidadeId"] = new SelectList(_context.Modalidades, "ModalidadeId", "ModalidadeId", chamado.ModalidadeId);
            ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "StatusId", chamado.StatusId);
            ViewData["TendenciaId"] = new SelectList(_context.Tendencias, "TendenciaId", "TendenciaId", chamado.TendenciaId);
            ViewData["UrgenciaId"] = new SelectList(_context.Urgencias, "UrgenciaId", "UrgenciaId", chamado.UrgenciaId);
            return View(chamado);
        }

        // GET: Chamados/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Chamados == null)
            {
                return NotFound();
            }

            var chamado = await _context.Chamados.FindAsync(id);
            if (chamado == null)
            {
                return NotFound();
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "ClienteId", "Nome", chamado.ClienteId);
            ViewData["GravidadeId"] = new SelectList(_context.Gravidades, "GravidadeId", "Descricao", chamado.GravidadeId);
            ViewData["ModalidadeId"] = new SelectList(_context.Modalidades, "ModalidadeId", "Descricao", chamado.ModalidadeId);
            ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "Descricao", chamado.StatusId);
            ViewData["TendenciaId"] = new SelectList(_context.Tendencias, "TendenciaId", "Descricao", chamado.TendenciaId);
            ViewData["UrgenciaId"] = new SelectList(_context.Urgencias, "UrgenciaId", "Descricao", chamado.UrgenciaId);
            return View(chamado);
        }

        // POST: Chamados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("ChamadoId,DataInicio,DataFechamento,Descricao,Diagnostico,Pendencia,Conclusao,StatusId,ModalidadeId,GravidadeId,UrgenciaId,TendenciaId,ClienteId")] Chamado chamado)
        {
            if (id != chamado.ChamadoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(chamado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChamadoExists(chamado.ChamadoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "ClienteId", "ClienteId", chamado.GravidadeId);
            ViewData["GravidadeId"] = new SelectList(_context.Gravidades, "GravidadeId", "GravidadeId", chamado.GravidadeId);
            ViewData["ModalidadeId"] = new SelectList(_context.Modalidades, "ModalidadeId", "ModalidadeId", chamado.ModalidadeId);
            ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "StatusId", chamado.StatusId);
            ViewData["TendenciaId"] = new SelectList(_context.Tendencias, "TendenciaId", "TendenciaId", chamado.TendenciaId);
            ViewData["UrgenciaId"] = new SelectList(_context.Urgencias, "UrgenciaId", "UrgenciaId", chamado.UrgenciaId);
            return View(chamado);
        }

        // GET: Chamados/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Chamados == null)
            {
                return NotFound();
            }

            var chamado = await _context.Chamados
                .Include(c => c.Cliente)
                .Include(c => c.Gravidade)
                .Include(c => c.Modalidade)
                .Include(c => c.Status)
                .Include(c => c.Tendencia)
                .Include(c => c.Urgencia)
                .FirstOrDefaultAsync(m => m.ChamadoId == id);
            if (chamado == null)
            {
                return NotFound();
            }

            return View(chamado);
        }

        // POST: Chamados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Chamados == null)
            {
                return Problem("Entity set 'AppDbContext.Chamados'  is null.");
            }
            var chamado = await _context.Chamados.FindAsync(id);
            if (chamado != null)
            {
                _context.Chamados.Remove(chamado);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChamadoExists(int id)
        {
            return _context.Chamados.Any(e => e.ChamadoId == id);
        }
    }
}

Kontrola/Kontrola/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kontrola.Context;
using Kontrola.Models;
using Microsoft.AspNetCore.Authorization;

namespace Kontrola.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ClientesController : Controller
    {
        private readonly AppDbContext _context;

        public ClientesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clientes.ToListAsync());
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.ClienteId == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClienteId,Nome,Cnpj,email,Telefone,TelefoneDois")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                // Verifique se todos os campos obrigatórios foram preenchidos
                if (string.IsNullOrEmpty(cliente.Nome) || string.IsNullOrEmpty(cliente.Cnpj) || string.IsNullOrEmpty(cliente.email) || string.IsNullOrEmpty(cliente.Telefone))
                {
                    // Lançar uma exceção personalizada ou retornar um BadRequestResult
                    // Aqui, estou lançando uma exceção InvalidOperationException
                    throw new InvalidOperationException("Todos os campos obrigatórios devem ser preenchidos.");
                }

                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClienteId,Nome,Cnpj,email,Telefone,TelefoneDois")] Cliente cliente)
        {
            if (id != cliente.ClienteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.ClienteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.ClienteId == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Clientes == null)
            {
                return Problem("Entity set 'AppDbContext.Clientes'  is null.");
            }
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente != null)
            {
                _context.Clientes.Remove(cliente);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
          return _context.Clientes.Any(e => e.ClienteId == id);
        }
    }
}

Kontrola/Kontrola/Views/Shared/_ChamadosHeader.cshtml
@model IEnumerable<Chamado>

@foreach (var model in Model)
{
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DataInicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataFechamento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modalidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gravidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Urgencia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tendencia)
        </th>
        <th></th>
    </tr>
}

Kontrola/Kontrola/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kontrola</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Kontrola.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

    <style>
        .nav-link {
            transition: all 0.2s ease-in-out;
        }
    </style>

</head>
<body>

    <header>
        <nav class="navbar navbar-dark bg-primary bg-gradient">
            <div class="container-fluid d-flex justify-content-between">
                <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="d-flex justify-content-center flex-grow-1">
                    <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Kontrola</a>
                </div>
                @await Html.PartialAsync("_LoginPartial")
                <div style="opacity: 0;">
                    <button class="btn btn-primary" style="visibility: hidden;">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
            </div>
        </nav>

        <div class="offcanvas offcanvas-start bg-light" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body text-center fs-3">
                <ul class="navbar-nav justify-content-center flex-grow-1 pe-3">
                    <li class="nav-item me-3">
                        <a class="nav-link text-dark @(ViewBag.OpcaoMenu == 1 ? "active bg-light border rounded shadow" : "")" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                    </li>
                    @if (@* User.IsInRole("Admin") || *@ User.IsInRole("Membro"))
                    {
                        <li class="nav-item me-3">
                            <a class="nav-link text-dark @(ViewBag.OpcaoMenu == 2 ? "active bg-light border rounded" : "")" asp-area="" asp-controller="Chamados" asp-action="IndexMembro">Chamados</a>
                        </li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item me-3">
                            <a class="nav-link text-dark @(ViewBag.OpcaoMenu == 2 ? "active bg-light border rounded" : "")" asp-area="" asp-controller="Chamados" asp-action="Index">Chamados</a>
                        </li>
                        <li class="nav-item me-3">
                            <a class="nav-link text-dark @(ViewBag.OpcaoMenu == 3 ? "active bg-light border rounded" : "")" asp-area="" asp-controller="Equipamentos" asp-action="Index">Equipamentos</a>
                        </li>

                        <li class="nav-item me-3">
                            <a class="nav-link text-dark @(ViewBag.OpcaoMenu == 5 ? "active bg-light border rounded" : "")" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>

                        <li class="nav-item me-3">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Register" style="color:white">&nbsp;Registrar novos usuarios</a>
                        </li>

                    }

                </ul>
            </div>

        </div>
    </header>



    <div class="container-fluid ">
        <main role="main" class="pb-3 w-100 h-100 p-3 text-dark ">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Kontrola - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>